export const SIMPLE_ICONS_CDN_BASE = "https://cdn.simpleicons.org";
export const LOBEHUB_ICONS_PNG_LIGHT_CDN_BASE =
  "https://unpkg.com/@lobehub/icons-static-png@latest/light";

export const CHANNEL_ICON_MAP: Record<string, string> = {
  discord: "discord",
  telegram: "telegram",
  tui: "ghostty",
  weixin: "wechat",
  wechat: "wechat",
  whatsapp: "whatsapp",
  slack: "slack",
  signal: "signal",
  googlechat: "googlechat",
  "google chat": "googlechat",
  imessage: "imessage",
  irc: "irc",
  line: "line",
};

export const PROVIDER_ICON_MAP: Record<string, string> = {
  vercel: "vercel",
  openrouter: "openrouter",
  "azure-openai": "azure-color",
  azure: "azure-color",
  openai: "openai",
  anthropic: "anthropic",
  claude: "anthropic",
  google: "google-color",
  gemini: "google-color",
  vertex: "google-color",
  deepseek: "deepseek-color",
  mistral: "mistral-color",
  meta: "meta-color",
  llama: "meta-color",
  cohere: "cohere-color",
  perplexity: "perplexity-color",
  groq: "groq",
  together: "together-color",
  togetherai: "together-color",
  fireworks: "fireworks-color",
  amazon: "aws-color",
  aws: "aws-color",
  bedrock: "aws-color",
  zhipu: "zhipu-color",
  moonshot: "moonshot",
  qwen: "qwen-color",
  alibaba: "alibaba-color",
  baichuan: "baichuan-color",
  minimax: "minimax-color",
  yi: "zeroone",
  "01": "zeroone",
  ai21: "ai21-brand-color",
  bytedance: "bytedance-color",
  doubao: "bytedance-color",
  spark: "spark-color",
  ollama: "ollama",
  huggingface: "huggingface-color",
  replicate: "replicate-brand",
  xai: "xai",
  grok: "xai",
  siliconflow: "siliconcloud-color",
  siliconcloud: "siliconcloud-color",
  stepfun: "stepfun-color",
  nvidia: "nvidia-color",
  cloudflare: "cloudflare-color",
  "workers-ai": "cloudflare-color",
  workersai: "cloudflare-color",
  sambanova: "sambanova-color",
  cerebras: "cerebras-brand-color",
};
